package POJOS;
// Generated 07-mar-2020 20:55:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CompraBackup generated by hbm2java
 */
public class CompraBackup  implements java.io.Serializable {


     private Integer id;
     private Tarjeta tarjeta;
     private ViajeBackup viajeBackup;
     private double importe;
     private int viajeros;
     private String localizador;
     private Set ocupacionBackups = new HashSet(0);

    public CompraBackup() {
    }

	
    public CompraBackup(Tarjeta tarjeta, ViajeBackup viajeBackup, double importe, int viajeros, String localizador) {
        this.tarjeta = tarjeta;
        this.viajeBackup = viajeBackup;
        this.importe = importe;
        this.viajeros = viajeros;
        this.localizador = localizador;
    }
    public CompraBackup(Tarjeta tarjeta, ViajeBackup viajeBackup, double importe, int viajeros, String localizador, Set ocupacionBackups) {
       this.tarjeta = tarjeta;
       this.viajeBackup = viajeBackup;
       this.importe = importe;
       this.viajeros = viajeros;
       this.localizador = localizador;
       this.ocupacionBackups = ocupacionBackups;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }
    public ViajeBackup getViajeBackup() {
        return this.viajeBackup;
    }
    
    public void setViajeBackup(ViajeBackup viajeBackup) {
        this.viajeBackup = viajeBackup;
    }
    public double getImporte() {
        return this.importe;
    }
    
    public void setImporte(double importe) {
        this.importe = importe;
    }
    public int getViajeros() {
        return this.viajeros;
    }
    
    public void setViajeros(int viajeros) {
        this.viajeros = viajeros;
    }
    public String getLocalizador() {
        return this.localizador;
    }
    
    public void setLocalizador(String localizador) {
        this.localizador = localizador;
    }
    public Set getOcupacionBackups() {
        return this.ocupacionBackups;
    }
    
    public void setOcupacionBackups(Set ocupacionBackups) {
        this.ocupacionBackups = ocupacionBackups;
    }




}


