package POJOS;
// Generated 07-mar-2020 20:55:13 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ViajeBackup generated by hbm2java
 */
public class ViajeBackup  implements java.io.Serializable {


     private Integer id;
     private Horario horario;
     private Date fecha;
     private int plazas;
     private Set compraBackups = new HashSet(0);

    public ViajeBackup() {
    }

	
    public ViajeBackup(Horario horario, Date fecha, int plazas) {
        this.horario = horario;
        this.fecha = fecha;
        this.plazas = plazas;
    }
    public ViajeBackup(Horario horario, Date fecha, int plazas, Set compraBackups) {
       this.horario = horario;
       this.fecha = fecha;
       this.plazas = plazas;
       this.compraBackups = compraBackups;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getPlazas() {
        return this.plazas;
    }
    
    public void setPlazas(int plazas) {
        this.plazas = plazas;
    }
    public Set getCompraBackups() {
        return this.compraBackups;
    }
    
    public void setCompraBackups(Set compraBackups) {
        this.compraBackups = compraBackups;
    }




}


