package POJOS;
// Generated 03-feb-2020 12:53:13 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private Integer id;
     private Viaje viaje;
     private Date fecha;
     private double importe;
     private int viajeros;
     private String localizador;
     private Set ocupacions = new HashSet(0);

    public Compra() {
    }

	
    public Compra(Viaje viaje, Date fecha, double importe, int viajeros, String localizador) {
        this.viaje = viaje;
        this.fecha = fecha;
        this.importe = importe;
        this.viajeros = viajeros;
        this.localizador = localizador;
    }
    public Compra(Viaje viaje, Date fecha, double importe, int viajeros, String localizador, Set ocupacions) {
       this.viaje = viaje;
       this.fecha = fecha;
       this.importe = importe;
       this.viajeros = viajeros;
       this.localizador = localizador;
       this.ocupacions = ocupacions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Viaje getViaje() {
        return this.viaje;
    }
    
    public void setViaje(Viaje viaje) {
        this.viaje = viaje;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public double getImporte() {
        return this.importe;
    }
    
    public void setImporte(double importe) {
        this.importe = importe;
    }
    public int getViajeros() {
        return this.viajeros;
    }
    
    public void setViajeros(int viajeros) {
        this.viajeros = viajeros;
    }
    public String getLocalizador() {
        return this.localizador;
    }
    
    public void setLocalizador(String localizador) {
        this.localizador = localizador;
    }
    public Set getOcupacions() {
        return this.ocupacions;
    }
    
    public void setOcupacions(Set ocupacions) {
        this.ocupacions = ocupacions;
    }




}


