package POJOS;
// Generated 19-feb-2020 17:25:42 by Hibernate Tools 4.3.1



/**
 * Ocupacion generated by hbm2java
 */
public class Ocupacion  implements java.io.Serializable {


     private Integer id;
     private Compra compra;
     private Viajero viajero;
     private int asiento;
     private double importe;

    public Ocupacion() {
    }

    public Ocupacion(Compra compra, Viajero viajero, int asiento, double importe) {
       this.compra = compra;
       this.viajero = viajero;
       this.asiento = asiento;
       this.importe = importe;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Viajero getViajero() {
        return this.viajero;
    }
    
    public void setViajero(Viajero viajero) {
        this.viajero = viajero;
    }
    public int getAsiento() {
        return this.asiento;
    }
    
    public void setAsiento(int asiento) {
        this.asiento = asiento;
    }
    public double getImporte() {
        return this.importe;
    }
    
    public void setImporte(double importe) {
        this.importe = importe;
    }




}


