package POJOS;
// Generated 19-feb-2020 19:59:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ruta generated by hbm2java
 */
public class Ruta  implements java.io.Serializable {


     private Integer id;
     private Estacion estacionByIdDestino;
     private Estacion estacionByIdOrigen;
     private Date duracion;
     private int kilometros;
     private float precio;
     private Set horarios = new HashSet(0);

    public Ruta() {
    }

	
    public Ruta(Estacion estacionByIdDestino, Estacion estacionByIdOrigen, Date duracion, int kilometros, float precio) {
        this.estacionByIdDestino = estacionByIdDestino;
        this.estacionByIdOrigen = estacionByIdOrigen;
        this.duracion = duracion;
        this.kilometros = kilometros;
        this.precio = precio;
    }
    public Ruta(Estacion estacionByIdDestino, Estacion estacionByIdOrigen, Date duracion, int kilometros, float precio, Set horarios) {
       this.estacionByIdDestino = estacionByIdDestino;
       this.estacionByIdOrigen = estacionByIdOrigen;
       this.duracion = duracion;
       this.kilometros = kilometros;
       this.precio = precio;
       this.horarios = horarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Estacion getEstacionByIdDestino() {
        return this.estacionByIdDestino;
    }
    
    public void setEstacionByIdDestino(Estacion estacionByIdDestino) {
        this.estacionByIdDestino = estacionByIdDestino;
    }
    public Estacion getEstacionByIdOrigen() {
        return this.estacionByIdOrigen;
    }
    
    public void setEstacionByIdOrigen(Estacion estacionByIdOrigen) {
        this.estacionByIdOrigen = estacionByIdOrigen;
    }
    public Date getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Date duracion) {
        this.duracion = duracion;
    }
    public int getKilometros() {
        return this.kilometros;
    }
    
    public void setKilometros(int kilometros) {
        this.kilometros = kilometros;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public Set getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Set horarios) {
        this.horarios = horarios;
    }




}


