package POJOS;
// Generated 03-mar-2020 10:51:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ViajeroBackup generated by hbm2java
 */
public class ViajeroBackup  implements java.io.Serializable {


     private Integer id;
     private String dni;
     private String nombre;
     private String apellidos;
     private Set ocupacionBackups = new HashSet(0);

    public ViajeroBackup() {
    }

	
    public ViajeroBackup(String dni, String nombre, String apellidos) {
        this.dni = dni;
        this.nombre = nombre;
        this.apellidos = apellidos;
    }
    public ViajeroBackup(String dni, String nombre, String apellidos, Set ocupacionBackups) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.ocupacionBackups = ocupacionBackups;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Set getOcupacionBackups() {
        return this.ocupacionBackups;
    }
    
    public void setOcupacionBackups(Set ocupacionBackups) {
        this.ocupacionBackups = ocupacionBackups;
    }




}


