package POJOS;
// Generated 19-feb-2020 17:25:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Viaje generated by hbm2java
 */
public class Viaje  implements java.io.Serializable {


     private Integer id;
     private Horario horario;
     private Date fecha;
     private int plazas;
     private Set compras = new HashSet(0);

    public Viaje() {
    }

	
    public Viaje(Horario horario, Date fecha, int plazas) {
        this.horario = horario;
        this.fecha = fecha;
        this.plazas = plazas;
    }
    public Viaje(Horario horario, Date fecha, int plazas, Set compras) {
       this.horario = horario;
       this.fecha = fecha;
       this.plazas = plazas;
       this.compras = compras;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getPlazas() {
        return this.plazas;
    }
    
    public void setPlazas(int plazas) {
        this.plazas = plazas;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


