package POJOS;
// Generated 18-feb-2020 13:25:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Viajero generated by hbm2java
 */
public class Viajero  implements java.io.Serializable {


     private Integer id;
     private String dni;
     private String nombre;
     private String apellidos;
     private int asiento;
     private Set ocupacions = new HashSet(0);

    public Viajero() {
    }

	
    public Viajero(String dni, String nombre, String apellidos, int asiento) {
        this.dni = dni;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.asiento = asiento;
    }
    public Viajero(String dni, String nombre, String apellidos, int asiento, Set ocupacions) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.asiento = asiento;
       this.ocupacions = ocupacions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public int getAsiento() {
        return this.asiento;
    }
    
    public void setAsiento(int asiento) {
        this.asiento = asiento;
    }
    public Set getOcupacions() {
        return this.ocupacions;
    }
    
    public void setOcupacions(Set ocupacions) {
        this.ocupacions = ocupacions;
    }




}


